[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14.2", features = ["coin_cbc"], default-features = false }
itertools = "0.14.0"
microlp = "0.2.11"
